package com.mehfatitem.imageUploadList.model;

public class MailTemplate {
	
	public String createforgetPasswordTemplate(String contact ,String email ,  String userName , String password , String year){
		String company = "ImageUploadList";
		String mailTitle = "ImageUploadList ® Þifremi unuttum";
		String locationUrl = "http://localhost:8080/imageUploadList/";
		String template = "<table width='600' border='0' cellspacing='0' cellpadding='5'><tbody><tr><td align='center' bgcolor='#fafafa'><table border='0'cellspacing='0' cellpadding='15'><tbody><tr><td align='center'><a href='"+locationUrl+" 'target='_blank' data-saferedirecturl='https://www.google.com/url?hl=tr&amp;q=http://imageUploadList.com&amp;source=gmail&amp;ust=1488459075083000&amp;usg=AFQjCNGV0399N8YTkIJXHzuesogP9D19oA'><img src='http://i.hizliresim.com/V0AOBZ.png' width='64' height='64' alt='imageUploadList-logo' class='CToWUd'></a></td></tr><tr><td align='center'style='font-family: Arial, Helvetica, sans-serif; font-size: 18px; font-weight: bold; color: #666666'>"+mailTitle+"</td></tr></tbody></table></td></tr><tr><td bgcolor='#31b0d5'><table width='100%' border='0' cellpadding='0' cellspacing='0'><tbody><tr><td align='left' style='font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #ffffff'><strong>"+ contact +"</strong>,<a style='color: #ffffff' href='http://"+email+"' target='_blank' data-saferedirecturl='https://www.google.com/url?hl=tr&amp;q=http://"+email+"&amp;source=gmail&amp;ust=1488459075083000&amp;usg=AFQjCNGLG8SBBOaztUlomN-G6an-oHYJlA'>"+email+"</a> Merhaba.</td></tr></tbody></table></td></tr><tr><td align='left'style='font-family: Arial, Helvetica, sans-serif; font-size: 11px; color: #9e9e9e'>Adýnýz ve soyadýnýz, bu mesajýn "+company+" ® tarafýndan gönderildiðine emin olmanýz için yazýlmýþtýr.</td></tr><tr><td><br><br><br> &nbsp;<b style='font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #666666'>"+contact+",</b><br><br> &nbsp;Talebiniz üzerine þifreniz sýfýrlanmýþtýr.<br> <br> &nbsp;Tüm "+company+" ® servislerine aþaðýdaki hesap bilgileriniz ile giriþ yapabilirsiniz.<br><br> &nbsp;Kullanýcý Adý: <strong>"+userName+"</strong><br>&nbsp;Þifre: <strong>"+password+"</strong></td></tr><tr><td><div style='color: #666; font-size: 13px'>Bu e-posta "+company+" ® tarafýndan gönderilmiþtir.<br> Copyright© 2017 - "+year+"</div></td></tr></tbody></table>";
		
		return template;
	}
	
	public String sendMailTemplateForJob(String contact , String email ,  String year , String mailTitle , String messageText ,  String locationUrl , String company){
		String template = "<table width='600' border='0' cellspacing='0' cellpadding='5'><tbody><tr><td align='center' bgcolor='#fafafa'><table border='0'cellspacing='0' cellpadding='15'><tbody><tr><td align='center'><a href='"+locationUrl+" 'target='_blank' data-saferedirecturl='https://www.google.com/url?hl=tr&amp;q=http://imageUploadList.com&amp;source=gmail&amp;ust=1488459075083000&amp;usg=AFQjCNGV0399N8YTkIJXHzuesogP9D19oA'><img src='http://i.hizliresim.com/V0AOBZ.png' width='64' height='64' alt='imageUploadList-logo' class='CToWUd'></a></td></tr><tr><td align='center'style='font-family: Arial, Helvetica, sans-serif; font-size: 18px; font-weight: bold; color: #666666'>"+mailTitle+"</td></tr></tbody></table></td></tr><tr><td bgcolor='#31b0d5'><table width='100%' border='0' cellpadding='0' cellspacing='0'><tbody><tr><td align='left' style='font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #ffffff'><strong>"+ contact +"</strong>,<a style='color: #ffffff' href='http://"+email+"' target='_blank' data-saferedirecturl='https://www.google.com/url?hl=tr&amp;q=http://"+email+"&amp;source=gmail&amp;ust=1488459075083000&amp;usg=AFQjCNGLG8SBBOaztUlomN-G6an-oHYJlA'>"+email+"</a> Merhaba.</td></tr></tbody></table></td></tr><tr><td align='left'style='font-family: Arial, Helvetica, sans-serif; font-size: 11px; color: #9e9e9e'>Adýnýz ve soyadýnýz, bu mesajýn "+company+" ® tarafýndan gönderildiðine emin olmanýz için yazýlmýþtýr.</td></tr><tr><td><br><br><br> &nbsp;<b style='font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #666666'>"+contact+",</b><br><br> &nbsp;"+messageText+"<br><br>&nbsp;Ýyi çalýþmalar dilerim.</br></strong></td></tr><tr><td><div style='color: #666; font-size: 13px'>Bu e-posta "+company+" ® tarafýndan gönderilmiþtir.<br> Copyright© 2017 - "+year+"</div></td></tr></tbody></table>";
		
		return template;
	}
}